# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stocktrade_pb2 as stocktrade__pb2


class StockTradeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Greeter = channel.unary_unary(
                '/stocktrade.StockTrade/Greeter',
                request_serializer=stocktrade__pb2.HelloRequest.SerializeToString,
                response_deserializer=stocktrade__pb2.HelloResponse.FromString,
                )
        self.Lookup = channel.unary_unary(
                '/stocktrade.StockTrade/Lookup',
                request_serializer=stocktrade__pb2.StockName.SerializeToString,
                response_deserializer=stocktrade__pb2.StockInfo.FromString,
                )
        self.Trade = channel.unary_unary(
                '/stocktrade.StockTrade/Trade',
                request_serializer=stocktrade__pb2.TradeInput.SerializeToString,
                response_deserializer=stocktrade__pb2.TradeStatus.FromString,
                )
        self.Update = channel.unary_unary(
                '/stocktrade.StockTrade/Update',
                request_serializer=stocktrade__pb2.UpdateInput.SerializeToString,
                response_deserializer=stocktrade__pb2.UpdateStatus.FromString,
                )


class StockTradeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Greeter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Lookup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Trade(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StockTradeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Greeter': grpc.unary_unary_rpc_method_handler(
                    servicer.Greeter,
                    request_deserializer=stocktrade__pb2.HelloRequest.FromString,
                    response_serializer=stocktrade__pb2.HelloResponse.SerializeToString,
            ),
            'Lookup': grpc.unary_unary_rpc_method_handler(
                    servicer.Lookup,
                    request_deserializer=stocktrade__pb2.StockName.FromString,
                    response_serializer=stocktrade__pb2.StockInfo.SerializeToString,
            ),
            'Trade': grpc.unary_unary_rpc_method_handler(
                    servicer.Trade,
                    request_deserializer=stocktrade__pb2.TradeInput.FromString,
                    response_serializer=stocktrade__pb2.TradeStatus.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=stocktrade__pb2.UpdateInput.FromString,
                    response_serializer=stocktrade__pb2.UpdateStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stocktrade.StockTrade', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StockTrade(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Greeter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stocktrade.StockTrade/Greeter',
            stocktrade__pb2.HelloRequest.SerializeToString,
            stocktrade__pb2.HelloResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Lookup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stocktrade.StockTrade/Lookup',
            stocktrade__pb2.StockName.SerializeToString,
            stocktrade__pb2.StockInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Trade(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stocktrade.StockTrade/Trade',
            stocktrade__pb2.TradeInput.SerializeToString,
            stocktrade__pb2.TradeStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/stocktrade.StockTrade/Update',
            stocktrade__pb2.UpdateInput.SerializeToString,
            stocktrade__pb2.UpdateStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
