# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stocktrade.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10stocktrade.proto\x12\nstocktrade\"\x1b\n\x0cHelloRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1c\n\rHelloResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x19\n\tStockName\x12\x0c\n\x04name\x18\x01 \x01(\t\"*\n\tStockInfo\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0e\n\x06volume\x18\x02 \x01(\x03\"R\n\nTradeInput\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x03\x12$\n\x04type\x18\x03 \x01(\x0e\x32\x16.stocktrade.TRADE_TYPE\"#\n\x0bTradeStatus\x12\x14\n\x0ctrade_status\x18\x01 \x01(\x11\"*\n\x0bUpdateInput\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x01\"%\n\x0cUpdateStatus\x12\x15\n\rupdate_status\x18\x01 \x01(\x11*\x1f\n\nTRADE_TYPE\x12\x07\n\x03\x42UY\x10\x00\x12\x08\n\x04SELL\x10\x01\x32\x83\x02\n\nStockTrade\x12@\n\x07Greeter\x12\x18.stocktrade.HelloRequest\x1a\x19.stocktrade.HelloResponse\"\x00\x12\x38\n\x06Lookup\x12\x15.stocktrade.StockName\x1a\x15.stocktrade.StockInfo\"\x00\x12:\n\x05Trade\x12\x16.stocktrade.TradeInput\x1a\x17.stocktrade.TradeStatus\"\x00\x12=\n\x06Update\x12\x17.stocktrade.UpdateInput\x1a\x18.stocktrade.UpdateStatus\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stocktrade_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRADE_TYPE._serialized_start=366
  _TRADE_TYPE._serialized_end=397
  _HELLOREQUEST._serialized_start=32
  _HELLOREQUEST._serialized_end=59
  _HELLORESPONSE._serialized_start=61
  _HELLORESPONSE._serialized_end=89
  _STOCKNAME._serialized_start=91
  _STOCKNAME._serialized_end=116
  _STOCKINFO._serialized_start=118
  _STOCKINFO._serialized_end=160
  _TRADEINPUT._serialized_start=162
  _TRADEINPUT._serialized_end=244
  _TRADESTATUS._serialized_start=246
  _TRADESTATUS._serialized_end=281
  _UPDATEINPUT._serialized_start=283
  _UPDATEINPUT._serialized_end=325
  _UPDATESTATUS._serialized_start=327
  _UPDATESTATUS._serialized_end=364
  _STOCKTRADE._serialized_start=400
  _STOCKTRADE._serialized_end=659
# @@protoc_insertion_point(module_scope)
